Added fit_regressor function documentation
UBC-MDS/simplerfit pull request #1
Opened 2022-01-21 05:09 UTC by rezam747

Added fit_regressor function documentation

2022-01-21 05:12 UTC, nd265 commented on R/fit_regressor.R
>  fit_regressor <- function(){}
```suggestion
fit_regressor <- function(){}
```

2022-01-21 05:26 UTC, nd265 approved these changes
Good job !!

2022-01-21 21:48 UTC, zzhzoe approved these changes

2022-01-22 03:32 UTC, Sanchit120496 requested changes
Input variable params needed

2022-01-22 10:56 UTC, nd265 approved these changes

2022-01-22 10:59 UTC, nd265 approved these changes

2022-01-22 11:07 UTC, nd265 requested changes
Input @params required

2022-01-22 17:41 UTC, nd265 approved these changes

2022-01-22 18:37 UTC, Sanchit120496 approved these changes

2022-01-22 18:37 UTC, merged