Add roxygen for eda functions
UBC-MDS/simplerfit pull request #7
Opened 2022-01-21 19:28 UTC by nd265

2022-01-21 21:47 UTC, zzhzoe approved these changes

2022-01-22 03:34 UTC, Sanchit120496 requested changes
plot_corr: Typo in line 6

2022-01-22 03:37 UTC, nd265 commented
> plot_corr: Typo in line 6

made the correction

2022-01-22 17:37 UTC, rezam747 approved these changes

2022-01-22 18:37 UTC, Sanchit120496 approved these changes

2022-01-22 18:37 UTC, merged